INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 'Badin', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, 'Dadu', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, 'Ghotki', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (4, 'Hyderabad', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (5, 'Jamshoro', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (6, 'Karachi Central', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (7, 'Karachi East', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (8, 'Karachi West', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (9, 'Karachi South', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (10, 'Karachi Korangi', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (11, 'Karachi Malir', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (12, 'Jacobabad', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (13, 'Kashmore', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (14, 'Khairpur', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (15, 'Larkana', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (16, 'Mitiari', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (17, 'MirPur Khas', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (18, 'Naushahro Feroze', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (19, 'Shaheed Benazirabad', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (20, 'Qambar Shahdadkot', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (21, 'Sanghar', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (22, 'Shikarpur', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (23, 'Sukkur', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (24, 'Tando Allahyar', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (25, 'Tando Muhammad Khan', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (26, 'Tharparkar', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (27, 'Thatta', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (28, 'Umerkot', NULL, NULL, NULL, NULL);
INSERT INTO `district_profiles` (`id`, `name`, `abbreviation`, `created_at`, `updated_at`, `deleted_at`) VALUES (29, 'Sujawal', NULL, NULL, NULL, NULL);
