INSERT INTO taluka_profiles set district_profile_id = 1, name = 'Badin';
INSERT INTO taluka_profiles set district_profile_id = 1, name = 'Matli';
INSERT INTO taluka_profiles set district_profile_id = 1, name = 'Shaheed Fazal Rahu';
INSERT INTO taluka_profiles set district_profile_id = 1, name = 'Tando Bago';
INSERT INTO taluka_profiles set district_profile_id = 1, name = 'Talhar';
INSERT INTO taluka_profiles set district_profile_id = 2, name = 'Dadu';
INSERT INTO taluka_profiles set district_profile_id = 2, name = 'Johi';
INSERT INTO taluka_profiles set district_profile_id = 2, name = 'Khairpur Nathan Shah';
INSERT INTO taluka_profiles set district_profile_id = 2, name = 'Mehar';
INSERT INTO taluka_profiles set district_profile_id = 3, name = 'Daharki';
INSERT INTO taluka_profiles set district_profile_id = 3, name = 'Ghotki';
INSERT INTO taluka_profiles set district_profile_id = 3, name = 'Khangarh (Khanpur)';
INSERT INTO taluka_profiles set district_profile_id = 3, name = 'Mirpur Mathelo';
INSERT INTO taluka_profiles set district_profile_id = 3, name = 'Ubauro';
INSERT INTO taluka_profiles set district_profile_id = 4, name = 'Hyderabad City';
INSERT INTO taluka_profiles set district_profile_id = 4, name = 'Hyderabad';
INSERT INTO taluka_profiles set district_profile_id = 4, name = 'Latifabad';
INSERT INTO taluka_profiles set district_profile_id = 4, name = 'Qasimabad';
INSERT INTO taluka_profiles set district_profile_id = 5, name = 'Kotri';
INSERT INTO taluka_profiles set district_profile_id = 5, name = 'Manjhand';
INSERT INTO taluka_profiles set district_profile_id = 5, name = 'Sehwan';
INSERT INTO taluka_profiles set district_profile_id = 5, name = 'Thano Bula Khan';
INSERT INTO taluka_profiles set district_profile_id = 6, name = 'Gulberg Town';
INSERT INTO taluka_profiles set district_profile_id = 6, name = 'Liaquatabad Town';
INSERT INTO taluka_profiles set district_profile_id = 6, name = 'New Karachi Town';
INSERT INTO taluka_profiles set district_profile_id = 6, name = 'North Nazimabad Town';
INSERT INTO taluka_profiles set district_profile_id = 7, name = 'Gulshan Town';
INSERT INTO taluka_profiles set district_profile_id = 7, name = 'Jamshed Town';
INSERT INTO taluka_profiles set district_profile_id = 7, name = 'Ferozabad';
INSERT INTO taluka_profiles set district_profile_id = 7, name = 'Gulshan e Iqbal';
INSERT INTO taluka_profiles set district_profile_id = 7, name = 'Gulzar e Hijri';
INSERT INTO taluka_profiles set district_profile_id = 8, name = 'Baldia Town';
INSERT INTO taluka_profiles set district_profile_id = 8, name = 'Kiamari Town';
INSERT INTO taluka_profiles set district_profile_id = 8, name = 'S.I.T.E. Town';
INSERT INTO taluka_profiles set district_profile_id = 8, name = 'Orangi Town';
INSERT INTO taluka_profiles set district_profile_id = 8, name = 'Harbour';
INSERT INTO taluka_profiles set district_profile_id = 8, name = 'Manghopir';
INSERT INTO taluka_profiles set district_profile_id = 8, name = 'Mauripur';
INSERT INTO taluka_profiles set district_profile_id = 8, name = 'Mominabad';
INSERT INTO taluka_profiles set district_profile_id = 9, name = 'Lyari Town';
INSERT INTO taluka_profiles set district_profile_id = 9, name = 'Saddar Town';
INSERT INTO taluka_profiles set district_profile_id = 9, name = 'Aram Bagh';
INSERT INTO taluka_profiles set district_profile_id = 9, name = 'Civil Line';
INSERT INTO taluka_profiles set district_profile_id = 9, name = 'Garden';
INSERT INTO taluka_profiles set district_profile_id = 10, name = 'Korangi Town';
INSERT INTO taluka_profiles set district_profile_id = 10, name = 'Landhi Town';
INSERT INTO taluka_profiles set district_profile_id = 10, name = 'Shah Faisal Town';
INSERT INTO taluka_profiles set district_profile_id = 10, name = 'Model Colony';
INSERT INTO taluka_profiles set district_profile_id = 11, name = 'Bin Qasim Town';
INSERT INTO taluka_profiles set district_profile_id = 11, name = 'Gadap Town';
INSERT INTO taluka_profiles set district_profile_id = 11, name = 'Malir Town';
INSERT INTO taluka_profiles set district_profile_id = 11, name = 'Jinnah';
INSERT INTO taluka_profiles set district_profile_id = 11, name = 'Ibrahim Hyderi';
INSERT INTO taluka_profiles set district_profile_id = 11, name = 'Murad Memon';
INSERT INTO taluka_profiles set district_profile_id = 11, name = 'Shah Murad';
INSERT INTO taluka_profiles set district_profile_id = 12, name = 'Garhi Khairo';
INSERT INTO taluka_profiles set district_profile_id = 12, name = 'Jacobabad';
INSERT INTO taluka_profiles set district_profile_id = 12, name = 'Thul';
INSERT INTO taluka_profiles set district_profile_id = 13, name = 'Kandhkot';
INSERT INTO taluka_profiles set district_profile_id = 13, name = 'Kashmore';
INSERT INTO taluka_profiles set district_profile_id = 13, name = 'Tangwani';
INSERT INTO taluka_profiles set district_profile_id = 14, name = 'Faiz Gunj';
INSERT INTO taluka_profiles set district_profile_id = 14, name = 'Gambat';
INSERT INTO taluka_profiles set district_profile_id = 14, name = 'Khairpur';
INSERT INTO taluka_profiles set district_profile_id = 14, name = 'Kingri';
INSERT INTO taluka_profiles set district_profile_id = 14, name = 'Kot Diji';
INSERT INTO taluka_profiles set district_profile_id = 14, name = 'Nara';
INSERT INTO taluka_profiles set district_profile_id = 14, name = 'Sobho Dero';
INSERT INTO taluka_profiles set district_profile_id = 14, name = 'Thari Mirwah';
INSERT INTO taluka_profiles set district_profile_id = 15, name = 'Bakrani';
INSERT INTO taluka_profiles set district_profile_id = 15, name = 'Dokri';
INSERT INTO taluka_profiles set district_profile_id = 15, name = 'Larkana';
INSERT INTO taluka_profiles set district_profile_id = 15, name = 'Rato Dero';
INSERT INTO taluka_profiles set district_profile_id = 16, name = 'Hala';
INSERT INTO taluka_profiles set district_profile_id = 16, name = 'Matiari';
INSERT INTO taluka_profiles set district_profile_id = 16, name = 'Saeedabad';
INSERT INTO taluka_profiles set district_profile_id = 17, name = 'Digri';
INSERT INTO taluka_profiles set district_profile_id = 17, name = 'Hussain Bux Marri';
INSERT INTO taluka_profiles set district_profile_id = 17, name = 'Jhuddo';
INSERT INTO taluka_profiles set district_profile_id = 17, name = 'Kot G. Muhammad';
INSERT INTO taluka_profiles set district_profile_id = 17, name = 'Mirpur Khas';
INSERT INTO taluka_profiles set district_profile_id = 17, name = 'Shujabad';
INSERT INTO taluka_profiles set district_profile_id = 17, name = 'Sindhri';
INSERT INTO taluka_profiles set district_profile_id = 18, name = 'Bhiria';
INSERT INTO taluka_profiles set district_profile_id = 18, name = 'Kandioro';
INSERT INTO taluka_profiles set district_profile_id = 18, name = 'Mehrabpur';
INSERT INTO taluka_profiles set district_profile_id = 18, name = 'Moro';
INSERT INTO taluka_profiles set district_profile_id = 18, name = 'Naushahro Feroze';
INSERT INTO taluka_profiles set district_profile_id = 19, name = 'Daur';
INSERT INTO taluka_profiles set district_profile_id = 19, name = 'Nawab Shah';
INSERT INTO taluka_profiles set district_profile_id = 19, name = 'Qazi Ahmed';
INSERT INTO taluka_profiles set district_profile_id = 19, name = 'Sakrand';
INSERT INTO taluka_profiles set district_profile_id = 20, name = 'Miro Khan';
INSERT INTO taluka_profiles set district_profile_id = 20, name = 'Nasirabad';
INSERT INTO taluka_profiles set district_profile_id = 20, name = 'Qambar';
INSERT INTO taluka_profiles set district_profile_id = 20, name = 'Kubo Saeed Khan';
INSERT INTO taluka_profiles set district_profile_id = 20, name = 'Shahdadkot';
INSERT INTO taluka_profiles set district_profile_id = 20, name = 'Sijawal Junejo';
INSERT INTO taluka_profiles set district_profile_id = 20, name = 'Warah';
INSERT INTO taluka_profiles set district_profile_id = 21, name = 'Jam Nawaz Ali';
INSERT INTO taluka_profiles set district_profile_id = 21, name = 'Khipro';
INSERT INTO taluka_profiles set district_profile_id = 21, name = 'Sanghar';
INSERT INTO taluka_profiles set district_profile_id = 21, name = 'Shahdadpur';
INSERT INTO taluka_profiles set district_profile_id = 21, name = 'Sinjhoro';
INSERT INTO taluka_profiles set district_profile_id = 21, name = 'Tando Adam';
INSERT INTO taluka_profiles set district_profile_id = 22, name = 'Garhi Yasin';
INSERT INTO taluka_profiles set district_profile_id = 22, name = 'Khanpur';
INSERT INTO taluka_profiles set district_profile_id = 22, name = 'Lakhi';
INSERT INTO taluka_profiles set district_profile_id = 22, name = 'Shikarpur';
INSERT INTO taluka_profiles set district_profile_id = 23, name = 'New Sukkur';
INSERT INTO taluka_profiles set district_profile_id = 23, name = 'Pano Akil';
INSERT INTO taluka_profiles set district_profile_id = 23, name = 'Rohri';
INSERT INTO taluka_profiles set district_profile_id = 23, name = 'Salehpat';
INSERT INTO taluka_profiles set district_profile_id = 23, name = 'Sukkur';
INSERT INTO taluka_profiles set district_profile_id = 24, name = 'Chamber';
INSERT INTO taluka_profiles set district_profile_id = 24, name = 'Jhando Mari';
INSERT INTO taluka_profiles set district_profile_id = 24, name = 'Tando Allahyar';
INSERT INTO taluka_profiles set district_profile_id = 25, name = 'Bulri Shah Karim';
INSERT INTO taluka_profiles set district_profile_id = 25, name = 'Tando Ghulam Hyder';
INSERT INTO taluka_profiles set district_profile_id = 25, name = 'Tando Muhammad Khan';
INSERT INTO taluka_profiles set district_profile_id = 26, name = 'Chachro';
INSERT INTO taluka_profiles set district_profile_id = 26, name = 'Dhali';
INSERT INTO taluka_profiles set district_profile_id = 26, name = 'Diplo';
INSERT INTO taluka_profiles set district_profile_id = 26, name = 'Islamkot';
INSERT INTO taluka_profiles set district_profile_id = 26, name = 'Kaloi';
INSERT INTO taluka_profiles set district_profile_id = 26, name = 'Mithi';
INSERT INTO taluka_profiles set district_profile_id = 26, name = 'Nagar ParKar';
INSERT INTO taluka_profiles set district_profile_id = 27, name = 'Ghorabi';
INSERT INTO taluka_profiles set district_profile_id = 27, name = 'Keti Bunder';
INSERT INTO taluka_profiles set district_profile_id = 27, name = 'Mirpur Sakro';
INSERT INTO taluka_profiles set district_profile_id = 27, name = 'Thatta';
INSERT INTO taluka_profiles set district_profile_id = 28, name = 'Kunri';
INSERT INTO taluka_profiles set district_profile_id = 28, name = 'Pithoro';
INSERT INTO taluka_profiles set district_profile_id = 28, name = 'Samaro';
INSERT INTO taluka_profiles set district_profile_id = 28, name = 'Umerkot';
INSERT INTO taluka_profiles set district_profile_id = 29, name = 'Jati';
INSERT INTO taluka_profiles set district_profile_id = 29, name = 'Kharo Chan';
INSERT INTO taluka_profiles set district_profile_id = 29, name = 'Mirpur Bathoro';
INSERT INTO taluka_profiles set district_profile_id = 29, name = 'Shah Bunder';
INSERT INTO taluka_profiles set district_profile_id = 29, name = 'Sujawal';
